name: Update Submodule

on:
  push:
    branches:
      - main

jobs:
  update_submodule:
    runs-on: ubuntu-latest

    permissions:
      contents: write  

    steps:
      - name: Checkout main repository
        uses: actions/checkout@v2
        with:
          repository: MrGoblings/MrGoblings
          token: ${{ secrets.GITHUB_TOKEN }} 
          path: main_repo 

      - name: Set up Git user
        run: |
          git config --global user.email "${{ secrets.GIT_USER_EMAIL }}"
          git config --global user.name MrGoblings

      - name: Update submodule
        run: |
          git -C main_repo submodule update --remote --merge  # Update submodules

      - name: Commit and push changes
        run: |
          git -C main_repo add .
          git -C main_repo commit -m "Automated: Update nvim submodule to latest" || echo "No changes to commit"
          git -C main_repo push
